## import libraries

In [1]:
import mediapipe as mp 
import cv2 
import argparse 
import os
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.preprocessing import LabelEncoder
from keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
import cv2
import numpy as np
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import time
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')


## Try with Taking A pic to predict

In [19]:
datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True
)

In [20]:
def capture_and_classify():
    # Countdown from 3 seconds
    for i in range(3, 0, -1):
        print(f"Countdown: {i}")
        time.sleep(1)

    # Capture a single frame from the webcam
    ret, frame = cap.read()

    # Face detection and emotion classification
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray)

    for (x, y, w, h) in faces:
        # Crop the detected face
        face_roi = frame[y:y+h, x:x+w]

        # Display the cropped face for visualization (optional)
        cv2.imshow('Cropped Face', face_roi)
        cv2.waitKey(0)
        cv2.destroyWindow('Cropped Face')

        # Resize the cropped face for emotion classification
        face_roi = cv2.resize(face_roi, (128, 128), interpolation=cv2.INTER_AREA)

        # Convert grayscale image to RGB
        roi_rgb = cv2.cvtColor(face_roi, cv2.COLOR_BGR2RGB)

        # Apply real-time data augmentation
        roi_rgb = img_to_array(roi_rgb)
        roi_rgb = roi_rgb.reshape((1,) + roi_rgb.shape)
        augmented_frame = np.array([datagen.random_transform(roi_rgb[0])])

        # Preprocess augmented frame and make prediction
        augmented_frame = augmented_frame / 255.0
        prediction = MobileNet_2_Expression_91_accuracy.predict(augmented_frame)[0]
        #emotion_index = np.argmax(prediction)
        emotion_index= 0 if prediction < 0.8 else 1
        label=emotion_labels_2[emotion_index]
       # if emotion_labels[emotion_index]=='happy':
            #emotion='happpy'

       # else : 
        #    emotion='unhappy'

        #print(f"Predicted emotion: {emotion_label}")

    return prediction,label,emotion_index

In [21]:
##### ### Assuming 'q' key to quit the loop, you can modify this according to your GUI framework.
cap = cv2.VideoCapture(0)
while True:
    key = input("Press any key to capture and classify, or 'q' to quit: ")
    if key.lower() == 'q':
        break
    else:
        prediction,label,index=capture_and_classify()            
        print(f'{prediction,label,index} ')
cap.release

cv2.destroyAllWindows()

Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.9281664], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.9653133], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.08563122], dtype=float32), 'happy', 0) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.50804263], dtype=float32), 'happy', 0) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.9997727], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.9999972], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  sq


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.85875964], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.9266635], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  s


Countdown: 3
Countdown: 2
Countdown: 1
(array([0.8718469], dtype=float32), 'unhappy', 1) 


Press any key to capture and classify, or 'q' to quit:  q


# Real-time 

In [15]:
import cv2
import numpy as np
from keras.preprocessing.image import img_to_array
from keras.applications.mobilenet import preprocess_input
import time

def capture_and_classify_real_time():
    # Load pre-trained model and other necessary resources
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    cap = cv2.VideoCapture(0)

    while True:
        # Capture frame-by-frame
        ret, frame = cap.read()

        # Convert frame to grayscale for face detection
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Detect faces in the frame
        faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

        for (x, y, w, h) in faces:
            # Crop the detected face
            face_roi = frame[y:y+h, x:x+w]

            # Resize the cropped face for emotion classification
            face_roi = cv2.resize(face_roi, (128, 128), interpolation=cv2.INTER_AREA)

            # Convert BGR to RGB and preprocess the face for classification
            face_rgb = cv2.cvtColor(face_roi, cv2.COLOR_BGR2RGB)
            face_array = img_to_array(face_rgb)
            print(face_array.shape)
            face_array = np.expand_dims(face_array, axis=0)
            print(face_array.shape)
            print(face_array)
            face_array = preprocess_input(face_array)
            print(face_array.shape)
            print(face_array)
            
            # Make prediction
            prediction = model.predict(face_array)[0]
            emotion_index = 0 if prediction < 0.5 else 1
            label = emotion_labels_2[emotion_index]

            # Draw rectangle around the detected face and label it with emotion
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(frame, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

        # Display the frame
        cv2.imshow('Face Classification', frame)

        # Exit loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release the capture
    cap.release()
    cv2.destroyAllWindows()


In [16]:
# Import necessary libraries and functions
import cv2
from keras.models import load_model

# Load the pre-trained model and other necessary resources
model = load_model('MobileNet_2_Expression_91_accuracy.h5')  # Provide the path to your model file
emotion_labels_2 = ["happy", "unhappy"]  # Define your emotion labels

# Call the function to start real-time face classification
capture_and_classify_real_time()


(128, 128, 3)
(1, 128, 128, 3)
[[[[160. 166. 158.]
   [161. 165. 158.]
   [160. 164. 157.]
   ...
   [145. 149. 149.]
   [146. 150. 149.]
   [146. 151. 150.]]

  [[160. 164. 157.]
   [161. 164. 157.]
   [161. 164. 157.]
   ...
   [146. 149. 148.]
   [147. 149. 147.]
   [145. 150. 148.]]

  [[161. 162. 156.]
   [161. 163. 156.]
   [161. 163. 157.]
   ...
   [145. 149. 145.]
   [146. 149. 145.]
   [144. 149. 145.]]

  ...

  [[103. 124. 154.]
   [ 87. 102. 138.]
   [ 76.  92. 122.]
   ...
   [ 27.  40.  57.]
   [ 27.  40.  58.]
   [ 27.  40.  57.]]

  [[102. 122. 151.]
   [ 80.  97. 130.]
   [ 72.  89. 119.]
   ...
   [ 28.  41.  59.]
   [ 26.  38.  56.]
   [ 26.  38.  56.]]

  [[101. 122. 149.]
   [ 76.  93. 124.]
   [ 70.  87. 116.]
   ...
   [ 28.  39.  59.]
   [ 28.  39.  57.]
   [ 27.  38.  57.]]]]
(1, 128, 128, 3)
[[[[ 0.254902    0.30196083  0.23921573]
   [ 0.26274514  0.2941177   0.23921573]
   [ 0.254902    0.28627455  0.2313726 ]
   ...
   [ 0.13725495  0.1686275   0.1686275 ]